export  const FETCH_PEOPLE_START ='FETCH_PEOPLE_START';
export  const FETCH_PEOPLE_SUCCESS ='FETCH_PEOPLE_SUCCESS';
export  const FETCH_PEOPLE_FAILURE ='FETCH_PEOPLE_FAILURE';

export  const FETCH_ALL_PEOPLE_START ='FETCH_ALL_PEOPLE_START';
export  const FETCH_ALL_PEOPLE_SUCCESS ='FETCH_ALL_PEOPLE_SUCCESS';
export  const FETCH_ALL_PEOPLE_FAILURE ='FETCH_ALL_PEOPLE_FAILURE';

export const SORT_PEOPLE = 'SORT_PEOPLE';

export const SEARCH_RECORD = 'SEARCH_RECORD';
