export  const FETCH_PEOPLE_START ='FETCH_PEOPLE_START';
export  const FETCH_PEOPLE_SUCCESS ='FETCH_PEOPLE_SUCCESS';
export  const FETCH_PEOPLE_FAILURE ='FETCH_PEOPLE_FAILURE';

// export  const FETCH_ALL_PEOPLE_START ='FETCH_ALL_PEOPLE_START';
// export  const FETCH_ALL_PEOPLE_SUCCESS ='FETCH_ALL_PEOPLE_SUCCESS';
// export  const FETCH_ALL_PEOPLE_FAILURE ='FETCH_ALL_PEOPLE_FAILURE';

export const SORT_PEOPLE = 'SORT_PEOPLE';

export const SEARCH_RECORD = 'SEARCH_RECORD';

export const ADD_RECORD = 'ADD_RECORD';

export const GOES_TO_NEXT_PAGE = "GOES_TO_NEXT_PAGE";


